fixing mongo connections error

diff --git a/.github/workflows/ci-app.yml b/.github/workflows/ci-app.yml
--- a/.github/workflows/ci-app.yml
+++ b/.github/workflows/ci-app.yml
@@ -13,11 +13,11 @@ jobs:
       - uses: actions/checkout@v2
       
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+          aws-region: ${{ secrets.AWS_REGION }}
       
       - name: Login to Amazon ECR
         id: login-ecr
@@ -86,6 +86,24 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           TERRAFORM_CLI_PATH: ${{ env.TERRAFORM_CLI_PATH }}
+      
+      - name: Install dependencies
+        run: |
+          pip install -r requirements.txt
+          pip install awscli
+      
+      - name: Get MongoDB Private IP
+        id: get_mongo_ip
+        run: |
+          echo "MONGO_IP=$(terraform -chdir=infra output -raw mongo_private_ip)" >> $GITHUB_ENV
+      
+      - name: Set up Kubeconfig
+        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
+      
+      - name: Replace Placeholders in Deployment
+        run: |
+          sed -i "s|\${MONGO_IP}|${{ env.MONGO_IP }}|g" app/k8s/deployment.yaml
+          sed -i "s|\${ECR_URL}|${{ steps.login-ecr.outputs.registry }}|g" app/k8s/deployment.yaml
       
       - name: Deploy to EKS
         env:
@@ -165,4 +183,17 @@ jobs:
             echo "--- Descripción del pod $POD ---"
             kubectl describe pod $POD || echo "No se pudo obtener la descripción del pod $POD"
             echo "--- Fin de la descripción del pod $POD ---"
+          done
+
+      - name: Get Pod Info for Diagnosis
+        if: failure() # Ejecutar solo si el paso anterior falla
+        run: |
+          echo "Deployment failed. Getting pod info..."
+          kubectl get pods -l app=wiz-app
+          PODS=$(kubectl get pods -l app=wiz-app -o jsonpath='{.items[*].metadata.name}')
+          for POD in $PODS; do
+            echo "--- Logs for pod $POD ---"
+            kubectl logs $POD --tail=50 || echo "Could not get logs for pod $POD"
+            echo "--- Describe pod $POD ---"
+            kubectl describe pod $POD || echo "Could not describe pod $POD"
           done
